---
singleQuote: true
trailingComma: 'all'
bracketSpacing: true
arrowParens: always
tabWidth: 4
overrides:
  - files: '*.md'
    options:
      tabWidth: 2
  - files: '*.json'
    options:
      tabWidth: 2
  - files: '*.yml'
    options:
      tabWidth: 2
